import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-solar-om-performance-guarantee-recovery",
  "engine": "recovery",
  "title": "Solar O&M Performance Guarantee Recovery",
  "shortTitle": "Solar OandM Performance Guarantee Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through solar o&m performance guarantee recovery",
  "industry": "Solar Asset Performance Recovery",
  "uiPort": 4627,
  "apiPort": 5627,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Solar O&M Performance Guarantee Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "recoveredCredits",
    "expectedKey": "eligibleCredits",
    "actualLabel": "Recovered Performance Credits",
    "expectedLabel": "Calculated Guarantee Recovery",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Solar O&M Performance Guarantee Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("oandm-warranty-agreement-library","SOP01","O&M warranty agreement library","Execute o&m warranty agreement library using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed o&m warranty agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","O&M warranty agreement library Reference","text","SOP01-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("site-equipment-registry","SOP02","Site equipment registry","Execute site equipment registry using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed site equipment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Site equipment registry Reference","text","SOP02-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("weather-irradiance-ingestion","SOP03","Weather irradiance ingestion","Execute weather irradiance ingestion using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed weather irradiance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Weather irradiance ingestion Reference","text","SOP03-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("meter-inverter-telemetry","SOP04","Meter inverter telemetry","Execute meter inverter telemetry using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed meter inverter telemetry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Meter inverter telemetry Reference","text","SOP04-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("expected-generation-model","SOP05","Expected generation model","Execute expected generation model using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed expected generation model decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Expected generation model Reference","text","SOP05-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("availability-calculation","SOP06","Availability calculation","Execute availability calculation using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed availability calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Availability calculation Reference","text","SOP06-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("excluded-event-validation","SOP07","Excluded event validation","Execute excluded event validation using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed excluded event validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Excluded event validation Reference","text","SOP07-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("curtailment-separation","SOP08","Curtailment separation","Execute curtailment separation using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed curtailment separation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Curtailment separation Reference","text","SOP08-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("performance-ratio-calculation","SOP09","Performance ratio calculation","Execute performance ratio calculation using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed performance ratio calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Performance ratio calculation Reference","text","SOP09-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("response-repair-sla","SOP10","Response repair SLA","Execute response repair sla using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed response repair sla decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Response repair SLA Reference","text","SOP10-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("liquidated-damages","SOP11","Liquidated damages","Execute liquidated damages using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed liquidated damages decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Liquidated damages Reference","text","SOP11-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("warranty-claim-linkage","SOP12","Warranty claim linkage","Execute warranty claim linkage using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed warranty claim linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Warranty claim linkage Reference","text","SOP12-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("provider-claim-package","SOP13","Provider claim package","Execute provider claim package using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed provider claim package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Provider claim package Reference","text","SOP13-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("credit-tracking","SOP14","Credit tracking","Execute credit tracking using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Credit tracking Reference","text","SOP14-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]}),
feature("site-vendor-analytics","SOP15","Site vendor analytics","Execute site vendor analytics using O&M and warranty agreements, solar sites, equipment, weather, irradiance, meters, inverters, expected generation, availability, exclusions, curtailment, repairs, and claims.","Produce a governed site vendor analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","O&M Provider / Solar Site","text","O&M Provider / Solar Site · Standard Case"],["caseReference","Site vendor analytics Reference","text","SOP15-2026-001"],["recoveredCredits","Recovered Performance Credits","currency",1086000],["eligibleCredits","Calculated Guarantee Recovery","currency",1281480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"recoveredCredits",subjects:["O&M warranty agreement library case","Site equipment registry case","Weather irradiance ingestion case","Meter inverter telemetry case","Expected generation model case"]})
]);
